# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0

/*==========================
      AWS ECS Service
===========================*/

resource "aws_ecs_service" "frontend" {
  name            = "frontend-service"
  cluster         = var.ecs_cluster_id
  task_definition = var.arn_task_definition_front
  desired_count   = 1
  launch_type     = "FARGATE"
  health_check_grace_period_seconds = 10

  network_configuration {
    subnets         = var.subnets_id
    security_groups = [var.frontsg]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = var.https_front
    container_name   = "frontend"
    container_port   = 3000
  }

   deployment_controller {
      type = "ECS"
    }

    lifecycle {
    // to avoid changes generated by autoscaling or new CodeDeploy changes
    ignore_changes = [desired_count, task_definition, load_balancer]
  }
}

resource "aws_ecs_service" "backend" {
  name            = "backend-service"
  cluster         = var.ecs_cluster_id
  task_definition = var.arn_task_definition_back
  desired_count   = 1
  launch_type     = "FARGATE"

  network_configuration {
    subnets         = var.subnets_id
    security_groups = [var.backsg]
    assign_public_ip = false
  }

  load_balancer {
    target_group_arn = var.https_back
    container_name   = "backend"
    container_port   = 5000
  }

   deployment_controller {
      type = "ECS"
    }

    lifecycle {
    // to avoid changes generated by autoscaling or new CodeDeploy changes
    ignore_changes = [desired_count, task_definition, load_balancer]
  }
}